service: python-ec2-start-stop
provider:
  name: aws
  runtime: python2.7
  region: us-east-1
  profile: serverless-admin
  memorySize: 128
  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "ec2:*"
     Resource: "*"

functions:
  start-ec2:
    handler: handler.start_ec2
    timeout: 60
    events:
      - 'schedule: rate(1 minutes)'
  stop-ec2:
    handler: handler.stop_ec2
    timeout: 60
    events:
      - 'schedule: rate(1 minutes)'

